# Generated by Django 2.2.3 on 2019-07-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True, verbose_name='username')),
                ('cardnumber', models.CharField(max_length=16, null=True, verbose_name='cardnumber')),
                ('nameoncard', models.CharField(max_length=30, null=True, verbose_name='nameoncard')),
                ('expirymonth', models.CharField(max_length=5, null=True, verbose_name='expirymonth')),
                ('expiryyear', models.CharField(max_length=5, null=True, verbose_name='expiryyear')),
                ('cvv', models.CharField(max_length=3, null=True, verbose_name='cvv')),
            ],
        ),
        migrations.AddField(
            model_name='savings',
            name='paid_sum',
            field=models.CharField(default='000000000', max_length=9, verbose_name='paid_sum'),
        ),
        migrations.AddField(
            model_name='savings',
            name='remaining_days',
            field=models.CharField(max_length=30, null=True, verbose_name='remaining_days'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amountpaid',
            field=models.CharField(max_length=10, null=True, verbose_name='amountpaid'),
        ),
    ]
