# Generated by Django 2.2.2 on 2019-07-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190711_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='cvv',
            field=models.CharField(max_length=5, null=True, verbose_name='cvv'),
        ),
    ]
